### PR TITLE
"disableRemoteMethod" compatible with loopback 3.x

### PR DESCRIPTION
**Pull request by upupzealot**
since Model.disableRemoteMethod has renamed into
Model.disableRemoteMethodByName in loopback 3.X

### CODE REVIEW

**Comment by Neil-UWA** [comment]
LGTM. Once I verify it, I will merge it.

**Comment by Neil-UWA** [comment]
@upupzealot  plz have a detailed look at the docs about disableRemoteMethod AND disableRemoteMethodByName,
http://apidocs.strongloop.com/loopback/#model-disableremotemethod
http://apidocs.strongloop.com/loopback/#model-disableremotemethodbyname

if you using disableRemoteMethodByName, then you have to passing the name with prototype if the method is defined on prototype.

It's better to stick to the predefined rules using `@` denotes static method, otherwise it's a instance method. i.e.

```
 var disableRemoteMethod = Model.disableRemoteMethodByName || Model.disableRemoteMethod;
var parameters = disableRemoteMethod.length;
    if (/^@/.test(method)) {
      parameters == 2 ?
        disableRemoteMethod.call(Model, method.replace(/^@/, ''), true) :
        disableRemoteMethod.call(Model, method.replace(/^@/, ''));
    } else {
       parameters == 2 ?
          disableRemoteMethod.call(Model, method,false):
          disableRemoteMethod.call(Model, 'prototype.'+method);
    }
```

also, plz update the tests for loopback@3.x feature. 
IF you don't have time, I will do the pr myself later

**Comment by upupzealot** [comment]
I just realized it's not a '**rename**' from disableRemoteMethodByName to disableRemoteMethod, but we should use disableRemoteMethodByName '**instead**' of disableRemoteMethod.

I updated this pr, please check again.

For the tests, I'm not sure what to do.
I would update this pr to make the tests in it to be compatible with loopback 3.x.

**Comment by Neil-UWA** [comment]
LGTM. MERGED. I will release it later

**Pull request merged**
